name: 'Kubernetes set context'
description: 'Login kubernetes'
inputs: 
  kubeconfig:
    description: 'Kubernetes Config'
    required: false
    default: ''
  clusterUrl:
    description: 'Cluster Url'
    required: false
    default: ''
  certificate:
    description: 'Certificate for connection to the cluster'
    required: false
    default: ''
  token:
    description: 'Service account token'
    required: false
    default: ''
  servicePrincipalId:
    description: 'Service Principal ID'
    required: false
    default: ''
  servicePrincipalKey:
    description: 'Service Principal Key'
    required: false
    default: ''
  tenantId:
    description: 'Tenant ID'
    required: false
    default: 'common'
  subscriptionId:
    description: 'Subscription ID'
    required: false
    default: ''
  resourceGroupName:
    description: 'Resource Group Name'
    required: false
    default: ''
  clusterName:
    description: 'AKS Cluster Name'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
