on: push

jobs:
  build:
    runs-on:
      pool: default
    actions:
      - run: echo hi
      - uses: ./login
        with:
          kubeconfig: someKubeConfig
        id: login
      - run: printenv
