on: [push, pull_request]

jobs:
  runs-on: default
  build:
    actions:
    - run: echo Hello World change
    - uses: ./hello-world-action
      with:
        who-to-greet: 'Mundo'
      id: hello
    - run: echo "The time was ${{ actions.hello.outputs.time }}"
