name: 'Kubernetes Login'
description: 'Login kubernetes'
inputs: 
  kubeconfig:
    description: 'Kubernetes Config'
    required: true
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node'
  main: 'lib/login.js'