name: 'AKS Login'
description: 'Login kubernetes'
inputs: 
  servicePrincipalId:
    description: 'Service Principal ID'
    required: true
    default: ''
  servicePrincipalKey:
    description: 'Service Principal Key'
    required: true
    default: ''
  tenantId:
    description: 'Tenant ID'
    required: true
    default: 'common'
  subscriptionId:
    description: 'Subscription ID'
    required: true
    default: ''
  resourceGroupName:
    description: 'Resource Group Name'
    required: true
    default: ''
  clusterName:
    description: 'AKS Cluster Name'
    required: true
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node'
  main: 'lib/aks.js'